Homework 2
AlekseiLysogora/AlekseiLysogora pull request #2
Opened 2020-12-10 13:37 UTC by AlekseiLysogora

2020-12-11 15:26 UTC, shoggy requested changes
Comments for ex1 also belong to ex2

## Test structure requirements:
- [x] Browser – Chrome
- [x] Window – maximized
- [x] Web Elements locators should not be autogenerated by browser plugins
  * Priority:
    * DOM locators
    * CSS selector
    * XPATH selector
- [x] All elements should have proper waits
- [x] Block (method) should start with comment line (ex. “// 2. Assert Browser title”) with step description which has been taken from this test case file
  * Block here means logical, not `{block}`
- [x] All code should according Java Code Convention
- [x] Tests should be run through the Test NG suite xml file.
- [x] Should be created maven profile for hw2
- [x] All tests must launch through the maven commands

## File placement requirements:
- [x] Classes should be placed into src/test/java/hw2 package and sub-packages
- [x] Homework should be developed in a new Java class
- [x] Each Exercise must be placed to dedicated package src/test/java/hw2/ex1, etc.
- [x] Test methods should have a name in accordance with checking functionality

## Tests
- [x] ex1
- [ ] ex2

2020-12-11 15:26 UTC, shoggy commented on src/test/resources/hw2/properties/config.properties
> +driverPath = src/main/resources/hw2/chromedriver_win32/chromedriver.exe
ChromeDriver is part of the test scope and would be better to put it in `src/test/...`

On the other side, you use bonigarcia:webdrivermanager and driver management can be delegated to it

2020-12-11 15:26 UTC, shoggy commented on pom.xml
> +            <version>3.141.59</version>
Move version to `properties` section please
and set `<scope>test`

2020-12-11 15:26 UTC, shoggy commented on pom.xml
> +            <version>4.2.2</version>
This version too

2020-12-11 15:26 UTC, shoggy commented on pom.xml
> +                <activeByDefault>false</activeByDefault>
`activeByDefault` is false by default, so this line can be omitted

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/AbstractPage.java
> +        try (final FileInputStream fis = new FileInputStream("src/test/resources/hw2/properties/exercise_1.properties"))
Reading resources from `src/.../resources/...` is not a good practice
https://mkyong.com/java/java-read-a-file-from-resources-folder/

hint, java.util.resourcebundle can be used here to avoid IOException handling if you want

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/webDriver/DriverManager.java
> +        driver.manage().window().maximize();
Let it start already maximized, use ChromeOptions, please

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/webDriver/DriverManager.java
> +        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
Do we really want long implicit waits?
Assume a situation when you check the presence of 6 static elements and non of them exists, but the driver will wait 10 seconds for each of them, 60 seconds of lost time.

Second situation. Somewhere next you use WebDriverWait with ExpectedConditions. As far as I remember WebDriverWait checks condition in loop, each time it tries to access element. Tricky moment here is that access to element wait implicitlyWait time. Unexpected behavior can be if you have WebDriverWait less than implicitlyWait

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/AbstractPage.java
> +            System.out.println("IOException for page (exercise 2)");
`exercise 2` -- copy-paste? :)

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +import org.openqa.selenium.support.ui.WebDriverWait;
unused imports, please remove

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +        return driver.getTitle().equals("Home Page") ? true : false;
Can be simplified
```suggestion
        return driver.getTitle().equals("Home Page");
```

The result of the method is not used anywhere...

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +        driver.findElement(By.xpath(loginCaret)).click();
waitForElementLocatedBy returns an element, so  you do not have to find it one more time
```suggestion
        String loginCaret = getPageProperty("loginCaret"); //xpath todo
        waitForElementLocatedBy(driver, By.xpath(loginCaret)).click();
```

same for the rest code

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +        waitForElementLocatedBy(driver, By.cssSelector(username));
This hw is focused on using Selenium. For this work would be better to inline selectors, instead of having them collected in one big-big file

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +        }
The compiler is OK with these blocks, but what for?

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +        waitForElementLocatedBy(driver, By.xpath(iframe));
If an element is not found then an exception will be raised

Some other solution is required

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +        driver.switchTo().frame(0);
here you are switching to some frame but should switch to a specific frame found in the previous line

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +        Assert.assertEquals(actual, expected);
you find an element by XPath `//input[@value='Frame Button']` and verify that `value='Frame Button'`. I think this condition will always be true ))

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +    }
assertion is missed

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/pages/HomePage.java
> +        }
You check items one by one. What will happen if e.g. second element will be missed?

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/runTest/RunTest.java
> +        driverManager = null;
I think DriverManager can be instantiated in the constructor and should not be nullified.

2020-12-11 15:26 UTC, shoggy commented on src/test/java/hw2/ex1/webDriver/DriverManager.java
> +        WebDriverManager.chromedriver().setup();
This looks like one-time action and can be performed in the constructor (or in static-initialization and `setupDriver()` can become static)

2020-12-11 15:26 UTC, shoggy commented on src/test/resources/hw2/properties/exercise_1.properties
> +rocketTxt = /html/body/div/div[2]/main/div[2]/div[2]/div[4]/div/span
Most of the locators can be rewritten using id and class attribute

2020-12-11 16:07 UTC, DmitryKhodakovsky requested changes

2020-12-11 16:07 UTC, DmitryKhodakovsky commented on src/test/java/hw1/dataProviders/DivisionDataProvider.java
> +package hw1.dataProviders;
Please do not forget make `rebase` to the *master* brach. There are should not be files from the hw1

2020-12-11 16:07 UTC, DmitryKhodakovsky commented on src/test/java/hw2/ex1/pages/HomePage.java
> +        waitForElementLocatedBy(driver, By.cssSelector(username));
Idea of this work that you will use pure selenium in the `@Test` methods

2020-12-11 16:07 UTC, DmitryKhodakovsky commented on src/test/java/hw2/ex2/runTest/RunTest.java
> +    }
Looks like code duplication for the `ex1` of the HW. Please extract common logic to the `BaseClass`

2020-12-16 17:16 UTC, shoggy requested changes
please update locators
```java
By.xpath("//ul[@class='sidebar-menu']") == By.css("ul.sidebar-menu")
By.xpath("//iframe[@id='frame']") == By.css("iframe#frame")
By.xpath("//a[contains(@href, 'different-elements.html')]") ==  By.css("a[href*='different-elements.html']")
```

2020-12-16 17:16 UTC, shoggy commented on src/test/java/hw2/ex2/runtest/RunTest.java
> +        softAssertion.assertAll();
assertAll should be executed at the end of `@Test` method

2020-12-16 17:16 UTC, shoggy commented on src/test/java/hw2/ex2/runtest/RunTest.java
> +
Move common code to the parent class

2020-12-16 17:16 UTC, shoggy commented on src/test/java/hw2/ex1/runtest/RunTest.java
> +        //         are displayed and they have proper texts
please use selectors that take not any `a` but only elements of the header menu

2020-12-16 17:16 UTC, shoggy commented on src/test/java/hw2/ex1/runtest/RunTest.java
> +                "The iframe with “Frame Button” isn't exist");
something is wrong here

2020-12-16 17:16 UTC, shoggy commented on src/test/java/hw2/ex1/runtest/RunTest.java
> +                texts, hasItem(containsString(expectedItems)));
softAssertion.assertEquals(elements, Arrays.asList(...))

2020-12-18 09:12 UTC, shoggy approved these changes

2020-12-18 09:27 UTC, DmitryKhodakovsky approved these changes
Approved

2020-12-18 09:41 UTC, merged